.licenserc.yaml
crates/core/src/table/meta_client.rs

ci: fix failing check and test case

---

.asf.yaml

Change issue and PR notification to the "commits" email list.

chore: fix asf notification

---

.github/workflows/ci.yml
README.md

Add codecov upload step after unit test.
Fixes #6

ci: fix codecov setup

---

crates/core/Cargo.toml
crates/core/src/config/read.rs
crates/core/src/config/table.rs
crates/core/src/storage/mod.rs
crates/core/src/table/fs_view.rs
crates/core/src/table/mod.rs
crates/core/src/table/timeline.rs

feat: add config validation when creating table

---

crates/core/src/config/internal.rs
crates/core/src/config/mod.rs
crates/core/src/table/mod.rs

- add internal.rs to host hudi internal configs
- add `hoodie.internal.skip.config.validation` to allow skipping

feat: add internal config to skip validation

---

Cargo.toml
crates/core/Cargo.toml
crates/datafusion/Cargo.toml
crates/tests/Cargo.toml
python/Cargo.toml

Remove redundant dependencies from workspace and crates.

build: clean up and trim down dependencies

---

crates/core/src/table/mod.rs

Take in any env var with prefix `AWS_`, `AZURE_`, and `GOOGLE_` to facilitate object_store creation.

feat: support taking env vars for cloud storages

---

CONTRIBUTING.md

Corrected typos and linked to source files for clarity.

docs: update CONTRIBUTING with minor changes

---

Cargo.toml
crates/datafusion/Cargo.toml
crates/datafusion/src/lib.rs
crates/hudi/Cargo.toml
crates/hudi/src/lib.rs
python/README.md
python/hudi/__init__.py
python/hudi/_internal.pyi
python/pyproject.toml
python/src/lib.rs

- Make `datafusion` a feature to hudi crate
- Add `__version__` to python package
- Add more info for package repositories

build: add info for rust and python artifacts

---

.github/workflows/ci.yml
python/pyproject.toml

ci: merge python code coverage report with rust

---

.github/PULL_REQUEST_TEMPLATE.md
.licenserc.yaml

Add PR template to emphasize on testing.

chore: add pull request template

---

.asf.yaml
.github/dependabot.yml

Enable dependabot https://docs.github.com/en/code-security/dependabot
Fixes #91

chore: enable dependabot

---

.github/workflows/ci.yml
.github/workflows/compliance.yml

- Only run tests when a change is made on any of the relevant paths.
- Move license and style checks to another CI workflow
Closes #84

ci: add path ignore files for ci

---

.github/workflows/code.yml
.github/workflows/pr.yml

Separate code checking from PR checking.
https://github.com/apache/hudi-rs/issues/109

chore: improve workflows for code checking and PR

---

python/Makefile

docs: update in-code comments

---

crates/core/src/config/internal.rs
crates/core/src/config/mod.rs
crates/core/src/config/read.rs
crates/core/src/config/table.rs
crates/core/src/config/utils.rs
crates/core/src/file_group/mod.rs
crates/core/src/file_group/reader.rs
crates/core/src/lib.rs
crates/core/src/storage/file_info.rs
crates/core/src/storage/file_stats.rs
crates/core/src/storage/utils.rs
crates/core/src/table/fs_view.rs
crates/core/src/table/partition.rs
crates/core/src/table/timeline.rs

Update in-code docs and tests for public APIs in `hudi-core`.
Closes #71

docs: add more in-code docs to hudi-core APIs

---

python/hudi/_internal.pyi

resolves: #70 
google style docstrings:
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

docs: add python binding docstrings

---

release/README.md
release/bump_version_in_main.sh

docs: add step-by-step release guide

---

Cargo.toml

Upgrade datafusion and object store to latest version

build(deps): upgrade datafusion and object store

---

Cargo.toml

DataFusion upgrade from 42.1.0 to 42.2.0
https://github.com/apache/datafusion/compare/42.1.0...42.2.0

build(deps): upgrade datafusion to 42.2.0

---

CONTRIBUTING.md
README.md
cliff.toml
release/README.md

Update release guide and dev guide.

docs: update release and dev guides

---

release/README.md
release/publish_src_release.sh

Update release script and the release guide.

chore: update release script and guide

---

CONTRIBUTING.md

Added some pull request requirements and directions to learn the architecture.

chore: update pull request guidelines for contributors

---

.asf.yaml
CONTRIBUTING.md
README.md
python/Makefile

Add more dev commands for formatting, and update project description.

chore: add more dev commands and update the project's short description

---

crates/core/src/table/builder.rs
crates/core/src/table/mod.rs

Add stubs for incremental APIs
- `read_incremental_records()`
- `read_incremental_changes()`
Also add a validation to restrict timeline layout version to 1.
#219

refactor: add API stubs for performing incremental queries

---

CONTRIBUTING.md
codecov.yml

Increase threshold from 5% to 10%.

chore: update codecov threshold

---

CONTRIBUTING.md

Clarify issues for contributors.
Mentioned in https://github.com/apache/hudi-rs/issues/209#issuecomment-2509629659

docs: clarify issues in the dev guide 

---

Cargo.toml
crates/core/Cargo.toml
crates/core/src/config/table.rs
crates/core/src/lib.rs
crates/core/src/storage/util.rs
crates/core/src/table/builder.rs
crates/core/src/table/mod.rs
crates/core/src/timeline/instant.rs
crates/core/src/timeline/mod.rs
crates/core/src/timeline/selector.rs

- Add `TimelineSelector` to help timeline load instants
- Add `TimelineTimezone` to support parsing timestamp when table is configured with timezone info
- Refactor timeline related structs
#9

feat: add `TimelineSelector` to support timeline loading

---

Cargo.toml
crates/core/Cargo.toml
crates/core/src/config/table.rs
crates/core/src/table/builder.rs
crates/core/src/table/mod.rs
crates/core/src/timeline/instant.rs
crates/core/src/timeline/mod.rs
crates/core/src/timeline/selector.rs
crates/core/tests/data/table_props_valid/.hoodie/hoodie.properties

Make `TimelineSelector` API easier to use for loading instants.
#9

refactor: improve `TimelineSelector` API

---

crates/core/src/config/read.rs
crates/core/src/table/fs_view.rs

- Add new config `hoodie.read.listing.parallelism` to control the parallelism listing when performing reads
- Minor refactor file system view APIs

feat: add `hoodie.read.listing.parallelism` config

---

crates/core/src/error.rs
crates/core/src/expr/filter.rs
crates/core/src/file_group/reader.rs
crates/core/src/table/partition.rs

Supporting passing generic filters to `FileGroupReader` to filter on returning records.

feat: support row filters for `FileGroupReader`

---

Cargo.toml
crates/core/Cargo.toml
crates/datafusion/Cargo.toml
crates/tests/Cargo.toml
python/Cargo.toml

- Minor version upgrade
- Clean up unused dependencies 
- Use better version numbers

build(deps): clean up dependencies

---

.github/workflows/ci.yml

Update Codecov Action from v4 to v5.
Closes https://github.com/apache/hudi-rs/issues/241
- Test workflow on my forked repository with my Codecov account

chore: update codecov-action to v5

---

README.md
crates/core/src/table/mod.rs
demo/README.md

Update readme to show the latest features and APIs.
Closes #123

docs: update `README.md` to show table API examples

---

.github/workflows/ci.yml
.github/workflows/code.yml
Cargo.toml
crates/core/src/table/mod.rs
demo/infra/runner/Dockerfile
demo/table-api-rust/Cargo.toml
python/Cargo.toml
python/src/internal.rs
python/src/lib.rs
rust-toolchain.toml

Update tool and arrow dependencies.

build(dep): upgrade rustc, arrow, and tarpaulin setting

---

Cargo.toml
crates/datafusion/Cargo.toml
crates/hudi/Cargo.toml

build(release): bump version to 0.4.0

---

release/verify_src_release.sh

Update the path pattern for excluding binary file scan.

chore: fix src verify script

---

.github/dependabot.yml
README.md

- Fix dependabot settings
- Update links for download badges and daft doc in README.md

chore: update dependabot settings and readme links

---

Cargo.toml
crates/core/src/config/table.rs
crates/core/src/table/mod.rs
crates/datafusion/src/lib.rs
demo/infra/runner/Dockerfile
demo/sql-datafusion/Cargo.toml
demo/table-api-rust/Cargo.toml
python/Cargo.toml
rust-toolchain.toml

build(deps): upgrade arrow, pyo3, datafusion, rustc

---

.github/workflows/ci.yml
.github/workflows/code.yml
python/pyproject.toml

chore: fix codecov report generation

---

.github/workflows/ci.yml
python/pyproject.toml

Codecov reported not able to process coverage report, which is caused by not finding source files. Check out code repo in the upload coverage step.

chore: fix codecov upload issue

---

.github/workflows/ci.yml

Update CI for python testing.
Add a job to upload nightly wheels for download.

chore(ci): update python test setup and upload nightly wheels

---

crates/core/src/file_group/reader.rs
crates/core/src/table/builder.rs
crates/core/src/table/mod.rs
crates/core/tests/data/table_props_valid_minimum/.hoodie/hoodie.properties
demo/apps/hudi-file-group-api/cpp/main.cpp
python/src/internal.rs
python/tests/test_file_group_read.py

fix: resolve env vars for creating standalone file group reader

---

.asf.yaml
README.md

Update docs and the project description and tag list.

docs: update readme docs and the project description

---

.asf.yaml

chore: update `asf.yaml` for more automation

---

Cargo.toml
cpp/CMakeLists.txt
cpp/Cargo.toml
crates/datafusion/Cargo.toml
crates/hudi/Cargo.toml

build(deps): add `-dev` for current development version

---

release/verify_src_release.sh

chore: update src verify script

---

.github/workflows/ci.yml
.github/workflows/code.yml
.gitignore
CONTRIBUTING.md
Makefile
demo/ci_run.sh
demo/infra/runner/Dockerfile
python/pyproject.toml

Use uv for Python package management
Close #346

build: use `uv` for Python package management

---

.asf.yaml

chore: enable discussions
