- .asf.yaml
- .github/workflows/ci.yml
- .gitignore
- .licenserc.yaml
- Cargo.toml
- LICENSE
- NOTICE
- README.md
- crates/core/Cargo.toml
- crates/core/src/error.rs
- crates/core/src/file_group/mod.rs
- crates/core/src/lib.rs
- crates/core/src/table/file_system_view.rs
- crates/core/src/table/meta_client.rs
- crates/core/src/table/mod.rs
- crates/core/src/timeline/mod.rs
- crates/datafusion/Cargo.toml
- crates/datafusion/src/bin/main.rs
- crates/datafusion/src/lib.rs
- crates/fs/Cargo.toml
- crates/fs/src/file_systems.rs
- crates/fs/src/lib.rs
- crates/fs/src/test_utils.rs
- crates/hudi/Cargo.toml
- crates/hudi/src/lib.rs
Leverage https://github.com/apache/skywalking-eyes to check source file license and setup GitHub action job.
Also configure `.asf.yaml` for repo settings.
> ci: setup ci for license file and headers

- .commitlintrc.yaml
- .github/workflows/pr.yml
Add github action job to enforce commit message conventional specified by https://www.conventionalcommits.org/en/v1.0.0/
> chore: add commit linting flow

- .github/workflows/ci.yml
- Cargo.toml
- Makefile
- crates/core/src/error.rs
- crates/core/src/file_group/mod.rs
- crates/core/src/table/file_system_view.rs
- crates/core/src/table/meta_client.rs
- crates/core/src/table/mod.rs
- crates/core/src/timeline/mod.rs
- crates/datafusion/src/bin/main.rs
- crates/datafusion/src/lib.rs
- crates/fs/src/file_systems.rs
- rust-toolchain.toml
Use `rustfmt` and `clippy` to enforce code style through CI check job.
Fixes #13
> style: enforce rust code style

- .github/workflows/ci.yml
- .gitignore
Use https://github.com/xd009642/tarpaulin to generate coverage file, which will be reported to https://app.codecov.io/gh/apache/hudi-rs
Fixes #6
> ci: use cargo tarpaulin to generate code coverage

- .github/workflows/ci.yml
codecov.io has started to require codecov token for upload coverage report for even public repos, and asf does not officially support using codecov, previous examples
- https://github.com/apache/pulsar/issues/19952#issuecomment-1487997039
- https://issues.apache.org/jira/browse/INFRA-24417
- https://issues.apache.org/jira/browse/INFRA-24399
We should integrate with sonar cloud instead. See https://infra.apache.org/services.html#qa
This PR first removes codecov integration to get CI green.
> ci: remove codecov to keep ci green

- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/error.rs
- crates/core/src/file_group/mod.rs
- crates/core/src/lib.rs
- crates/core/src/storage/file_metadata.rs
- crates/core/src/storage/mod.rs
- crates/core/src/table/config.rs
- crates/core/src/table/fs_view.rs
- crates/core/src/table/mod.rs
> feat: use `object_store` for common storage APIs

- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/file_group/mod.rs
- crates/core/src/storage/file_info.rs
- crates/core/src/storage/file_stats.rs
- crates/core/src/storage/mod.rs
- crates/core/src/storage/utils.rs
- crates/core/src/table/fs_view.rs
- crates/core/src/table/mod.rs
- crates/core/src/timeline/mod.rs
- crates/datafusion/src/lib.rs
- python/Cargo.toml
- python/hudi/_internal.pyi
- python/hudi/_utils.py
- python/hudi/table.py
- python/pyproject.toml
- python/src/lib.rs
- python/tests/__init__.py
- python/tests/conftest.py
- python/tests/test_table_read.py
- Support python APIs to retrieve the latest file slices
- Support python APIs to read file slice as `pyarrow.RecordBatch`
- Implement Rust logic to fetch num records in parquet file
- Implement Rust logic to read parquet file into `arrow.RecordBatch`
Fixes #29
> feat: implement Rust and Python APIs to read file slices

- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/file_group/mod.rs
- crates/core/src/lib.rs
- crates/core/src/storage/mod.rs
- crates/core/src/table/fs_view.rs
- crates/core/src/table/mod.rs
- crates/core/src/table/timeline.rs
- crates/datafusion/Cargo.toml
- crates/datafusion/src/lib.rs
- python/Cargo.toml
- python/hudi/_internal.pyi
- python/src/lib.rs
- python/tests/test_table_read.py
- adopt Arc and DashMap for file system view, timeline, and table structs
- change some return types to Result and add handlings
> refactor: improve thread safety and error handling

- crates/core/src/config/mod.rs
- crates/core/src/config/read.rs
- crates/core/src/table/mod.rs
- crates/datafusion/src/lib.rs
- python/src/lib.rs
- python/tests/test_table_read.py
Support passing option `hoodie.read.as.of.timestamp` and perform time travel query.
Fixes #39
> feat: support time travel with read option

- .github/workflows/ci.yml
- release/create_src_release.sh
- release/verify_src_release.sh
- add script to create src release
- add script to verify src release
- enable release branch CI
> chore: add scripts to streamline source release

- Cargo.toml
Use the exact version for core dependencies, arrow and datafusion, to prevent incompatible minor upgrade done implicitly.
> build: use exact versions for arrow and datafusion

- crates/core/Cargo.toml
- crates/core/src/storage/mod.rs
- crates/core/src/table/fs_view.rs
- crates/core/src/table/mod.rs
- crates/core/src/table/timeline.rs
- crates/datafusion/Cargo.toml
- crates/datafusion/src/lib.rs
Reading Hudi tables from an object store, s3 in this case, was failing due to the object store not being registered with Datafusion. 
Before the changes in this PR, the following error was encountered:
```
Error: Internal("No suitable object store found for s3://test-hudi-rs/. See `RuntimeEnv::register_object_store`")
```
Datafusion requires the object store to be registered. Refer [here](https://github.com/apache/datafusion/blob/fa50636c6aec0f321212ed8678c77de25b71a8f9/datafusion/core/src/execution/context/mod.rs#L375).
- `Storage` and `FileSystemView` have public struct fields `object_store` and `storage`. There should be a better way to expose these to the `datafusion` crate to be able to register them.
> fix: register object store with datafusion

- .github/workflows/pr.yml
Disable due to `pull_request_target` is not allowed as per https://infra.apache.org/github-actions-policy.html
> chore: disable labeler due to permission and policy

- Cargo.toml
- crates/core/src/table/mod.rs
- crates/datafusion/src/lib.rs
- rust-toolchain.toml
- Update the project dependencies to DataFusion 41.0.0 and Arrow 52.2.0.
- Rust version bump to 1.76
> build: bump up DataFusion to version 41, Arrow to 52.2

- crates/core/src/table/mod.rs
- crates/core/tests/data/config/hudi-defaults.conf
Use a common test function to create fixture `Table` without running config validation.
> refactor: extract common test code for creating table

- .github/workflows/pr.yml
`line 3: syntax error near unexpected token '('`
The syntax error near the unexpected token '(') is due to the parentheses being treated as part of the shell's syntax. Enclosing the entire string in quotes should fix it.
fixes: #136
> chore(ci): fix PR title linting to support change scope

- crates/core/src/file_group/mod.rs
- crates/core/src/storage/file_stats.rs
- python/hudi/_internal.pyi
- python/src/internal.rs
- python/tests/test_table_read.py
Extract parquet's row groups size bytes info and save it in hudi core model `FileStats`.
> feat: add base file records' in-memory size to `FileStats`

- crates/core/src/config/internal.rs
- crates/core/src/config/mod.rs
- crates/core/src/config/read.rs
- crates/core/src/config/table.rs
- crates/core/src/file_group/mod.rs
- crates/core/src/lib.rs
- crates/core/src/storage/mod.rs
- crates/core/src/table/mod.rs
#71 
- add hudi-core doc in-code
some doc code will be test
> docs: add hudi core API docs with examples

- crates/core/src/table/mod.rs
Some tables may not have `hoodie.datasource.write.drop.partition.columns`, the table validation should treat it as false by default.
> fix: handle validating table when `DropsPartitionFields` not present

- .github/workflows/ci.yml
- Cargo.toml
- crates/datafusion/src/lib.rs
- python/Cargo.toml
- python/pyproject.toml
Upgrade datafusion from 0.41 to 0.42 and its dependencies (arrow, pyo3).
gil-refs are deprecated in pyo3 0.22.2, therefore I removed it, it was causing arrow compilation to fail.
Drop support for Python3.8 as it won't receive security updates starting next month.
Bump required python to min. 3.9.
resolves #143
> build(deps): upgrade datafusion from 0.41 to 0.42

- crates/core/src/table/fs_view.rs
- crates/core/src/table/mod.rs
Fix the partition loading logic such that it
- does not skip relevant partitions 
- makes file group loading parallelized
#47
> fix: make partition loading more efficient

- Cargo.toml
bump arrow from 53.0.0 to 53.1.0
resolves: #143
> build(deps): upgrade arrow dependencies

- .github/ISSUE_TEMPLATE/feature_request.yml
I noticed I can only file bug report, but can't file in a feature request.
This introduces a template for a feature request for GH issue.
> chore: add feature request template for GH issues

- crates/datafusion/src/lib.rs
resolves: #150 
This allows datafusion users to register an external hudi table and query it like so:
```sql
CREATE EXTERNAL TABLE trips STORED AS HUDI LOCATION 'path';
SELECT * FROM trips;
```
> feat: implement datafusion TableProviderFactory

- crates/datafusion/src/lib.rs
Minor code improvement to make main branch cov report green.
#150
> refactor: minor improvement to fix coverage report status

- crates/core/src/table/mod.rs
- crates/datafusion/src/lib.rs
- python/hudi/__init__.py
- python/hudi/_internal.pyi
- python/src/internal.rs
- python/tests/test_table_read.py
Rename api `split_file_slices()` to `get_file_slices_splits()` and handle empty table case.
> fix: improve api to get file slices splits

- crates/datafusion/src/lib.rs
Fix DataFusion integration get schema API to handle empty table case - the original Hudi table api returns an Err when retrieving schema fails. The DataFusion API expects a legit SchemaRef to return, so change to return empty schema when Hudi table api gives Err.
Resolves #126
> fix: handle schema retrieval for datafusion api

- Cargo.toml
- crates/datafusion/src/lib.rs
- rust-toolchain.toml
Closes #196 
Upgrade versions for Df and arrow.
And upgrade rust to 1.79
> build(deps): upgrade Datafusion, Arrow, and Rust versions

- python/Cargo.toml
`pyo3` cannot be upgraded to 0.23.2 right now due to `arrow-rs`'s current version not having upgraded to `pyo3` in their latest release
> build(deps): update pyo3 requirement from 0.22.2 to 0.22.4

- crates/datafusion/src/lib.rs
Mentioned in #125 
Updated crate's docs to account for `CREATE EXTERNAL TABLE`
> docs: add `CREATE EXTERNAL TABLE` example in datafusion crate

- crates/core/src/error.rs
- crates/core/src/expr/filter.rs
- crates/core/src/table/partition.rs
- crates/datafusion/src/lib.rs
- crates/datafusion/src/util/expr.rs
- Rename `PartitionFilter` to `SchemableFilter` for generic use
- Fix missing `Operator::NotEq` support
- Add ergonomic functions for composing `Filter`s, such as `col("foo").eq("a")`
Closes #160 
Follow up #203
> refactor: enhance `Filter` and related structs

- .github/workflows/ci.yml
- demo/.env
- demo/app/.gitignore
- demo/app/python/src/__init__.py
- demo/app/python/src/main.py
- demo/app/rust/Cargo.toml
- demo/app/rust/src/main.rs
- demo/compose.yaml
- demo/infra/mc/Dockerfile
- demo/infra/mc/prepare_data.sh
- demo/infra/runner/Dockerfile
- demo/run_app.sh
- Add `demo/` to show an e2e docker setup for querying a test hudi table stored on minio. Show both rust and python usage examples.
- Make assertions in the demo apps and make them run with CI as integration tests.
Closes #81 
Reworked based on #112
> feat: add demo app and integration tests

- Cargo.toml
- crates/core/src/error.rs
- crates/core/src/file_group/builder.rs
- crates/core/src/file_group/mod.rs
- crates/core/src/storage/mod.rs
- crates/core/src/table/mod.rs
- crates/core/src/timeline/mod.rs
- crates/core/src/timeline/selector.rs
- python/hudi/_internal.pyi
- python/src/internal.rs
- python/tests/test_table_incremental_read.py
For performing incremental queries (latest-state mode), added table APIs
```
read_incremental_records(&self, start_timestamp: &str, end_timestamp: Option<&str>)
read_incremental_records(self, start_timestamp: str, end_timestamp: Optional[str])
```
Closes #9
> feat: implement incremental query for COW tables

- CONTRIBUTING.md
- codecov.yml
Update codecov config to give 5% leniency for project and 10% leniency for PRs.
> chore: update codecov config

- crates/core/src/config/table.rs
- crates/core/src/error.rs
- crates/core/src/lib.rs
- crates/core/src/merge/mod.rs
- crates/core/src/merge/record_merger.rs
- Basic implementation of `RecordMerger` to perform merge using different strategies.
- Support `AppendOnly` and `OverwriteWithLatest` merge strategies set via `hoodie.table.record.merge.strategy`
Closes #246
> feat: implement basic record merge semantics

- crates/core/src/error.rs
- crates/core/src/lib.rs
- crates/core/src/merge/mod.rs
- crates/core/src/merge/record_merger.rs
- crates/core/src/metadata/meta_field.rs
- crates/core/src/metadata/mod.rs
- crates/core/src/util/arrow.rs
- crates/core/src/util/mod.rs
- Add `MetaField` enum for Hudi meta fields.
- Consider `_hoodie_commit_seqno` for merging when precombine values are equal
> fix: include commit_seqno for merge order

- crates/core/src/file_group/builder.rs
- crates/core/src/file_group/file_slice.rs
- crates/core/src/file_group/mod.rs
- crates/core/src/metadata/mod.rs
- crates/core/src/table/fs_view.rs
- crates/core/src/table/listing.rs
- crates/core/src/table/mod.rs
- crates/core/src/table/partition.rs
- python/src/internal.rs
- Move file listing logic from `FileSystemView` to `FileLister`
- Change FileGroup and FileSlice partition_path to accept empty string for non-partitioned tables
- File system view will refresh relevant partitions for loading the latest file groups when a query needs to scan those
- Skip Iceberg's and Delta's metadata dirs when listing top level dirs
> refactor: improve file system view's listing flow

- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/metadata/meta_field.rs
- crates/core/src/table/mod.rs
Avoid resolving table schema for composing incremental query filters.
> refactor: use static MetaField schema for incr query

- crates/core/src/config/read.rs
- crates/core/src/table/mod.rs
- crates/datafusion/src/lib.rs
Add a read config `hoodie.read.use.read_optimized.mode` to allow performing read-optimized queries for MOR table.
Closes #79
> feat: support MOR read-optimized query

- crates/core/src/expr/filter.rs
- crates/core/src/file_group/reader.rs
- crates/core/src/table/mod.rs
- crates/core/src/util/mod.rs
- crates/datafusion/src/lib.rs
- crates/datafusion/src/util/expr.rs
- python/src/internal.rs
Replace `Filter` from being used as public API args. Use tuple of str instead for simpler invocation.
> refactor: remove use of `Filter` from public APIs

- .github/workflows/ci.yml
I made some changes to reduce the `ci.yml` time for Rust tests.
Closes https://github.com/apache/hudi-rs/issues/218
The changes made are as follows:
1. Added the [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache) action.  
This allows us to cache dependencies and build artifacts so repeated builds can skip redownloading or recompiling crates that are unchanged.
2. Added the `--skip-clean` argument to tarpaulin.  
By default, tarpaulin behaves as if `--force-clean` is set, which deletes existing build artifacts and prevents reuse of cached builds.  
With `--skip-clean`, the cached artifacts from `Swatinem/rust-cache` can be used before running tests.  
(See [Tarpaulin documentation on recompilation](https://github.com/xd009642/tarpaulin?tab=readme-ov-file#recompilation) for …
> chore(ci): add rust dependency caching with rust-cache action

- crates/core/src/table/fs_view.rs
- crates/core/src/table/mod.rs
- crates/core/src/timeline/mod.rs
- crates/core/src/timeline/selector.rs
When getting excluding file groups, it should consider the as-of timestamp if provided.
> fix: handle as-of timestamp for excluding file groups

- crates/core/src/config/mod.rs
- crates/core/src/file_group/mod.rs
Updated based on https://github.com/apache/hudi-rs/pull/214
> docs: add in-code docs for `FileGroup`

- crates/core/src/config/read.rs
- crates/core/src/file_group/file_slice.rs
- crates/core/src/file_group/reader.rs
- crates/core/src/table/mod.rs
- crates/core/src/timeline/mod.rs
- crates/datafusion/src/lib.rs
- python/hudi/_internal.pyi
- python/src/internal.rs
- python/tests/test_table_builder.py
- python/tests/test_table_read.py
- Add new table API `get_file_slices_between()` to support reading incremental file slices for engine integration
- Add time range configs for file group reader to support filtering records and log file scanning
- `hoodie.read.file_group.start_timestamp`
- `hoodie.read.file_group.end_timestamp` 
- Remove `hoodie.read.as.of.timestamp` from configs in favor of passing time travel timestamp via API
- Refactor the table APIs impl to provide clearer flow of reading file slices
- Push down the logic of checking base file only and composing instant range to file group reader
- Add the corresponding Python APIs
Closes #271
> feat: add APIs to support incremental query impl

- crates/core/src/file_group/base_file.rs
- crates/core/src/file_group/builder.rs
- crates/core/src/file_group/file_slice.rs
- crates/core/src/file_group/log_file/mod.rs
- crates/core/src/file_group/mod.rs
- crates/core/src/table/mod.rs
- crates/core/src/timeline/mod.rs
When incrementally fetch changed file groups from commit metadata, the same file groups should be merged such that all relevant log files are included.
> fix: build up incremental file groups

- .github/workflows/ci.yml
- .github/workflows/code.yml
- CONTRIBUTING.md
- Makefile
- demo/run_demo.sh
- python/tests/conftest.py
Refactoring Makefile such that it works under the root dir.
fixes #281
> refactor: move `Makefile` to root directory

- .github/workflows/ci.yml
- Cargo.toml
- crates/core/src/timeline/instant.rs
When DST changes, the test case is affected due to using `Local::now()`. Fixed the timezone to ensure consistent test expectation.
Also fixed the patch version for chrono due to https://www.reddit.com/r/rust/comments/1iz0py1/crate_build_is_broken_by_chrono_and_arrowarinth/
> fix: make local timezone test more robust

- crates/core/src/table/builder.rs
- crates/core/src/table/mod.rs
- crates/core/src/table/validation.rs
- crates/core/src/util/collection.rs
Add `OptionResolver` to handle resolving options during table instance creation. The logic can be re-used for creating file group reader.
> refactor: use `OptionResolver` to handle options

- .github/workflows/release.yml
The actions-rs org has been archived for years at this point and it doesn't look like it's coming back. For security reasons we are going to remove it from the list of allowed actions in the org soon. (See https://github.com/apache/infrastructure-actions)
> chore(ci): replace archived actions-rs actions

- crates/core/src/file_group/record_batches.rs
- crates/core/src/merge/ordering.rs
- crates/core/src/merge/record_merger.rs
- crates/core/src/record/mod.rs
- crates/core/src/schema/delete.rs
When ordering value from delete block is 0 (a special value to indicate ordering value should not be used), ignore the event time ordering, and use commit time as fall back.
> fix: handle zero event time ordering

- Cargo.toml
- crates/core/src/avro_to_arrow/README.md
- crates/core/src/table/partition.rs
- crates/datafusion/src/lib.rs
- crates/test/Cargo.toml
- demo/apps/datafusion/Cargo.toml
- demo/apps/hudi-table-api/rust/Cargo.toml
- python/Cargo.toml
DataFusion 45.0 -> 46.0
Arrow 54.1 -> 54.2
Fix DataFusion API usage based on the new version. Update test cases to cover filter pushdown.
> build(deps): upgrade datafusion arrow, and restrict deps upgrade to patch-level

- crates/core/src/table/mod.rs
- crates/core/src/util/collection.rs
Add `get_file_slices_splits_between()` API, enables parallel processing of incremental data changes between timestamps.
closes #403
> feat: add `get_file_slices_splits_between` API

- crates/core/src/table/validation.rs
Remove support for Hudi table version 5 from validation logic.
closes #372
> feat: remove table version 5 support

- crates/core/src/util/collection.rs
- python/hudi/_internal.pyi
- python/src/internal.rs
Rename parameter `n` to `num_splits` in all file slice splitting APIs for better readability.
fixes: #423
> refactor: rename variable names in splitting table APIs

- crates/core/src/config/mod.rs
- crates/core/src/config/read.rs
- crates/core/src/config/table.rs
- crates/core/src/file_group/log_file/reader.rs
- crates/core/src/file_group/reader.rs
- crates/core/src/file_group/record_batches.rs
- crates/core/src/merge/ordering.rs
- crates/core/src/merge/record_merger.rs
- crates/core/src/schema/resolver.rs
- crates/core/src/table/listing.rs
- crates/core/src/table/mod.rs
- crates/core/src/table/partition.rs
- crates/core/src/table/validation.rs
- crates/core/src/timeline/selector.rs
- crates/datafusion/src/lib.rs
- delete custom `.to::<T>()` method from `HudiConfigValue`
- replaced all `.to::<Type>()` calls with standard `.into()` patterns across the codebase
closes #368
> refactor: replace custom `.to::()` with `into()` for `HudiConfig` conversions

- crates/core/src/storage/mod.rs
- crates/core/src/table/listing.rs
Moves `.crc` file filtering logic from table layer to storage layer to make sure all storage consumers automatically exclude `.crc` files.
closes: #438
> refactor: ignore `.crc` files at storage level
